In [1]:
import numpy as np

Задание с предыдущего урока:
__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [38]:
from scipy.linalg import lu

In [131]:
def triangle_solve(matrix, free_coef, descending=False):
    res = np.zeros_like(free_coef, dtype=float)
    if descending:
        for index, element in reversed(list(enumerate(free_coef))):
            res[index, 0] = (element[0]-matrix.dot(res)[index,0])/matrix[index, index]
    else:
        for index, element in enumerate(free_coef):
            res[index, 0] = (element[0]-matrix.dot(res)[index,0])/matrix[index, index]
    return res

In [129]:
def linear_system_solve(coef_matrix, free_element_vector):
    permutation, L, U = lu(coef_matrix)
    perm_inv = np.linalg.inv(permutation)
    y = triangle_solve(L, perm_inv.dot(free_element_vector))
    x = triangle_solve(U,y,descending=True)
    return x

In [133]:
%%time
A = np.array([[2,1,3],[11,7,5],[9,8,4]])
b = np.array([[1],[-6],[-5]])
linear_system_solve(A,b)

Wall time: 0 ns


array([[-1.00000000e+00],
       [ 1.46549439e-16],
       [ 1.00000000e+00]])

In [134]:
%%time
np.linalg.solve(A,b)

Wall time: 0 ns


array([[-1.00000000e+00],
       [ 2.44249065e-16],
       [ 1.00000000e+00]])

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [4]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
U, d, V = np.linalg.svd(A)

In [11]:
U

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [12]:
V

array([[ 0.07116451,  0.71702467,  0.69340553],
       [-0.36737824,  0.66514082, -0.65009301],
       [-0.92734505, -0.20847855,  0.31075368]])

In [6]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = d
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [10]:
np.round(U.dot(D.dot(V)))

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

а)евклидова норма равна первому сингулярному числу

In [20]:
D[0,0]

8.824868854820442

б)Вычислим норму Фробениуса по формуле $$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [33]:
np.sqrt(sum(sum(map(lambda x: pow(x,2), D))))

11.045361017187261